### ISSUE TITLE
Cannot find module './core/rapid'

### ISSUE THREAD

**Issue by webdevian** [rapidjs/rapid.js#20]
Error thrown on linux when booting a file that extends RapidJS.

```
Error: Cannot find module './core/rapid'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/lib/jenkins/workspace/vernight_highstreet_develop-Z4EJGYUMCGUJXLSZ5RREIJWO3ZYMIKFLYOSGEMPIHGYF6PMVVKIQ/node_modules/rapid.js/dist/rapid.js:3:14)
```

My dist folder looks like this: 
![image](https://user-images.githubusercontent.com/5087745/33272700-d5ba382a-d382-11e7-922e-08e9b345bc61.png)

Looks like a problem with case insensitivity

**Comment by drewjbartlett** [comment]
The latest version renamed all the files and folders to lowercase. Maybe try uninstalling and reinstalling the package. Let me know if that helps!

**Comment by drewjbartlett** [comment]
@webdevian actually I noticed that the dist path hadn't been updated for the case. I just published a patch that fixes that :)
